services:
  propogator:
    container_name: propogator
    build:
      context: .
      dockerfile: src/propogator/Dockerfile
    volumes:
      - ./events.json:/app/events.json
    command: 
      - --event_file
      - /app/events.json
      - --api_address
      - http://host.docker.internal:8080
      - --period
      - "5"
